### ISSUE TITLE
Opinion on recoll

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [thesephist/monocle#1]
Hi!

Very intrigued by your project. I was wondering about your thoughts on personnal desktop search engines like [recoll](https://www.lesbonscomptes.com/recoll/).

I personnaly export a lot of my personnal informations as text file to index them in recoll.

I would have thought that forking a software like recoll to add your own tokenizer etc would have been a time saver. It also exists without GUI.

Curious about why you went from scratch.

**Comment by thesephist** [comment]
Few reasons, none of them that great:

1. I wanted to learn how a basic FTS engine worked, so wanted to build my own. This is the main reason.
2. I needed something that worked on mobile b/c I'm frequently outside. Recoil seems to have a so-so mobile web app. I also could have chosen some other search library for the web, too, but didn't because of reason no. 1.
3. Some stuff I need to index are not always locally available (they're twitter exports, exports of my notes apps, etc.) that interface thru an API or manual one-time export.

It's kind of like asking, there are so many computers out there, why would you build your own computer?  Well, sometimes it's just fun to build your own :) And often useful to understand everything under the hood to extend / modify it to suit my needs.
